### ISSUE TITLE
Add class parameter to search 

### ISSUE THREAD

**Issue by kurzum** [dbpedia/lookup-application#2]
`QueryClass=place&QueryString=berlin`
QueryClass

**Comment by holycrab13** [comment]
added a more generic approach, see documentation

**Comment by holycrab13** [comment]
To be more specific: 
The index needs to index the type (for example as "resourceType")

Then do `/search?query=Berlin&resourceType=Place&resourceTypeRequired=true`

**Comment by holycrab13** [comment]
You can now define aliases for query paramters, so doing `QueryClass=place&QueryString=berlin` is possible
