### ISSUE TITLE
Java IllegalMonitorStateException

### ISSUE THREAD

**Issue by wenzi3241** [dbpedia/lookup-application#7]
I'm running on Linux without root permission. The following error happens after I run "docker-compose up". Could anyone tell what this error means? And how should I fix it? 

=========================================
dbpedia-lookup_1  | Copying .war to tomcat webapps directory.
dbpedia-lookup_1  | =========================================
dbpedia-lookup_1  | Done! Starting tomcat...
dbpedia-lookup_1  | =========================================
dbpedia-lookup_1  | Tomcat started.
dbpedia-lookup_1  | Running...
dbpedia-lookup_1  | Setting up watches.  Beware: since -r was given, this may take a while!
dbpedia-lookup_1  | Watches established.
dbpedia-lookup_1  |     at org.apache.jena.tdb2.loader.base.LoaderOps.inputFile(LoaderOps.java:108)
dbpedia-lookup_1  |     at org.apache.jena.tdb2.loader.base.LoaderBase.loadOne(LoaderBase.java:125)
dbpedia-lookup_1  |     at org.apache.jena.tdb2.loader.base.LoaderBase.lambda$load$0(LoaderBase.java:102)
dbpedia-lookup_1  |     at java.util.Arrays$ArrayList.forEach(Arrays.java:3880)
dbpedia-lookup_1  |     at org.apache.jena.tdb2.loader.base.LoaderBase.load(LoaderBase.java:99)
dbpedia-lookup_1  |     at org.apache.jena.tdb2.loader.DataLoader.load(DataLoader.java:114)
dbpedia-lookup_1  |     at org.dbpedia.lookup.IndexMain.main(IndexMain.java:155)
dbpedia-lookup_1  |     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
dbpedia-lookup_1  |     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
dbpedia-lookup_1  |     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
dbpedia-lookup_1  |     at java.lang.reflect.Method.invoke(Method.java:498)
dbpedia-lookup_1  |     at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
dbpedia-lookup_1  |     at java.lang.Thread.run(Thread.java:748)
dbpedia-lookup_1  | [INFO] Finish - index OSP
dbpedia-lookup_1  | [INFO] Finish - index POS
dbpedia-lookup_1  | [INFO] Finish - index SPO
dbpedia-lookup_1  | java.lang.IllegalMonitorStateException
dbpedia-lookup_1  |     at java.util.concurrent.locks.ReentrantReadWriteLock$Sync.tryRelease(ReentrantReadWriteLock.java:371)
dbpedia-lookup_1  |     at java.util.concurrent.locks.AbstractQueuedSynchronizer.release(AbstractQueuedSynchronizer.java:1261)
dbpedia-lookup_1  |     at java.util.concurrent.locks.ReentrantReadWriteLock$WriteLock.unlock(ReentrantReadWriteLock.java:1131)
dbpedia-lookup_1  |     at org.apache.jena.dboe.transaction.txn.TransactionCoordinator.finishExclusiveMode(TransactionCoordinator.java:413)
dbpedia-lookup_1  |     at org.apache.jena.tdb2.loader.main.LoaderMain.finishBulk(LoaderMain.java:263)
dbpedia-lookup_1  |     at org.dbpedia.lookup.IndexMain.main(IndexMain.java:160)
dbpedia-lookup_1  |     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
dbpedia-lookup_1  |     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
dbpedia-lookup_1  |     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
dbpedia-lookup_1  |     at java.lang.reflect.Method.invoke(Method.java:498)
dbpedia-lookup_1  |     at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
dbpedia-lookup_1  |     at java.lang.Thread.run(Thread.java:748)

**Comment by holycrab13** [comment]
Can you post the collection URI and config file that you used?

**Comment by wenzi3241** [comment]
Yes, it is the one in this repo.

**Comment by holycrab13** [comment]
The exception was thrown due to bad handling of another Exception thrown by the Jena RDF parser. The Parser is unable to read one of the files in the data collection and instead of skipping it just stopped. This should be fixed now. 

Note that the approach of this app for indexing the data is:
1) Load the data to a TDB2 database
2) Retrieve (key,value) pairs for indexing via SPARQL queries.

This means that for now the entire dataset has to be loaded first. For the DBpedia dataset this can take quite some time, disk space and memory.  I will provide a pre-built index for the latest DBpedia dataset asap (once the release is somewhat stable).

**Comment by holycrab13** [comment]
The documentation is now a lot more extensive, please verify if the issue can be closed. Cheers!

**Comment by holycrab13** [comment]
Closed due to inactivity
